### ISSUE TITLE
Should not use classes to declare types

### ISSUE THREAD

**Issue by gomain** [TheCre8tor/bim_launcher#1]
https://github.com/TheCre8tor/bim_launcher/blob/0d6c2b322b6cbe01187d41bd897b8cbda5df7e3a/src/external_service.ts#L28-L34

Classes serve the purpose OOP style encapsulation. I.e. such that data can also hold _methods_ that interact on it. It also allows the concept of _constructor_, a special function that returns data of such type.

I would argue that OOP style inherently carries its own complexity. Usage of `new`, definition of `this`, size of the class declaration (imagine a class with 100 methods).

In this instance, the better alternative is to just declare types with `type` or `interface` keyword and a _smart_ constructor.
```ts
type Version = { 
  attribute: Map<string, string>;
};

function Version(attribute: Map<string, string>): Version { 
  return { attribute };
};
```
We could also reduce this type to
```ts
type Version = Map<string, string>;
```
This makes the constructor redundant.

Typescript does not provide the elegance of [nominal types](https://en.wikipedia.org/wiki/Nominal_type_system) as we get from _tuple structs_ in Rust. Classes offer some level of nominal types (via prototype), but I would argue it's not worth the complexities it brings.

**Comment by TheCre8tor** [comment]
You are right, Gomain.
That was what I did when I first wrote the code,
I only changed it at the last minute to follow the Rust Struct style.

Thanks, I will put it in order.

**Comment by TheCre8tor** [comment]
And thanks for the indept explaination.
