### ISSUE TITLE
Decouple compiling from running

### ISSUE THREAD

**Issue by gomain** [TheCre8tor/bim_launcher#2]
https://github.com/TheCre8tor/bim_launcher/blob/0d6c2b322b6cbe01187d41bd897b8cbda5df7e3a/package.json#L8

Use of `ts-node` is probably debatable. I'm more inclined to to _compile_ typescript code and run the compiled code with `node` rather than have this happen behind the curtains.

Such that this script would probably be
```json
    "compile": "tsc",
    "start": "node ./dist/src/index.js",
    "run": "compile && start"
```

**Comment by TheCre8tor** [comment]
Great, fixed.
